---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: Pod
metadata:
  name: download-and-mount-pod
spec:
  initContainers:
    - name: init-container
      image: google/cloud-sdk:latest
      command: ["sh", "-c", "gsutil cp -r gs://gke-testing-007/testing/* /tmp/"]
      volumeMounts:
        - name: downloaded-file
          mountPath: /data
        - name: shared-data
          mountPath: /shared
  containers:
    - name: user-container
      image: alpine:latest
      command: ["sh", "-c", "ls -lh /tmp/"]
      volumeMounts:
        - name: downloaded-file
          mountPath: /data
        - name: shared-data
          mountPath: /shared
  volumes:
    - name: downloaded-file
      emptyDir: {}
    - name: shared-data
      persistentVolumeClaim:
        claimName: my-pvc
