apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME-deployment
  labels:
    app: DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: DEPLOYMENT_NAME
    spec:
      containers:
      - name: DEPLOYMENT_NAME
        image: IMAGE_NAME
        ports:
        - containerPort: 30333
