---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
# this pvc will be used to store mysql database
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-init-demo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-script-downloader
        image: google/cloud-sdk:latest
        command: ["sh", "-c", "gsutil cp -r gs://gke-testing-007/testing/* /tmp/"]
        volumeMounts:
        - name: init-script
          mountPath: /tmp
      containers:
      - image: asia-south1-docker.pkg.dev/cssp-dhiway/main/sparknet:2024-11-04-12-54-boot-node-7
        command: ["sh", "-c", "ls -lh /cord/"]
        name: mysql
        volumeMounts:
        - name: data
          mountPath: /mnt
        - name: init-script
          mountPath: /cord
      volumes:
      - name: init-script
        persistentVolumeClaim:
          claimName: my-pvc
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
