apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-1-deployment
  labels:
    app: validator-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-1
  template:
    metadata:
      labels:
        app: validator-1
    spec:
      containers:
      - name: validator-1
        image: asia-south1-docker.pkg.dev/cssp-dhiway/main/validator-1:2024-05-04-09-30
        ports:
        - containerPort: 30333
