name: CI Pipeline

env:
  ENV: Dev

run-name: Deploy from ${{ github.ref_name }} by @${{ github.actor }} in $ENV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building..."
