name: CI Pipeline

run-name: Deploy from ${{ github.ref_name }} by @${{ github.actor }} in ${{ vars.ENV }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building..."
