name: Call a reusable workflow

on:
  workflow_dispatch:
#  workflow_call:
#    inputs:
#      source_branch:
#        description: 'Source branch with SHA'
#        required: true
#        type: string
  
env:
  SERVICE_NAME: CSSP

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: cssp007/github-action/.github/workflows/secrets-in-gcp.yaml@main
    with:
      SERVICE_NAME: ${{ env.SERVICE_NAME }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
