name: Create Secrets in GCP

on:
  push:
    branches:
      - main
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_GKE }}"
         
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
#      - name: Create secret
#        run: gcloud secrets create my-secret --data-file=secrets.txt

      - name: Upload nodes key to GCS
        run: find . -type f ! -name 'gha-creds-*.json' | xargs gsutil -m cp -r -I gs://gke-testing-007/testing/
