name: Create Secrets in GCP

on:
  push:
    branches:
      - main
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_GKE }}"
         
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
#      - name: Create secret
#        run: gcloud secrets create my-secret --data-file=secrets.txt

      - name: Upload nodes key to GCS
        run: gsutil -m cp -r ./* gs://gke-testing-007/testing/
        
      - name: Delete unwated files
        run: gsutil rm gs://gke-testing-007/testing/gha-creds-*.json

      - name: Configure kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          install-missing: true

      - name: Authenticate with GKE Cluster
        run: |-
          gcloud auth list
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials cssp-testing --region asia-south1 --project cssp-dhiway

      - name: Apply YAML file
        run: |
          kubectl apply -f validator.yml
          
